# server port
server:
  port: 8081

spring:
    application: 
        name: Match

    datasource:
        url: jdbc:h2:mem:match
        username: sa
        password: 
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

# actuator endpoints

management:
    endpoints:
        web:
            exposure:
                include: '*'